### ISSUE TITLE
What are these extra output files?

### ISSUE THREAD

**Issue by wsnoble** [wenbostar/pepmap#3]
The output directory contains four files.  What are the two with very long numbers in their filenames?

```
 peptide_map.txt
 peptide_map_0_8970847779235342412.txt
 peptide_map_detail.txt
 peptide_map_detail_0_6751965274122702676.txt
```

**Comment by wenbostar** [comment]
The two files with long names are intermediate files used to generate the two final files (peptide_map.txt,  peptide_map_detail.txt). They are useful in debugging.

**Comment by wsnoble** [comment]
I think you should delete them at the end of the run.

**Comment by wenbostar** [comment]
Great suggestion. The intermediate files are deleted in the end of the mapping in the latest version.
